# Site specific settings
title: "iamzerg.github.io/blog"
name: "Blog"
keywords: "Key, words, about, this, website"
url: "https://iamzerg.github.io"
baseurl: "/blog"
description: "Learn to code.  Learn to live."
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
